"""empty message

Revision ID: ba6d87f9d136
Revises: 5efd0f2b519e
Create Date: 2020-12-05 20:59:39.348044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6d87f9d136'
down_revision = '5efd0f2b519e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('stats_avatar_id_fkey', 'stats', type_='foreignkey')
    op.create_foreign_key(None, 'stats', 'users', ['user_id'], ['id'])
    op.drop_column('stats', 'avatar_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('avatar_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.create_foreign_key('stats_avatar_id_fkey', 'stats', 'avatars', ['avatar_id'], ['id'])
    op.drop_column('stats', 'user_id')
    # ### end Alembic commands ###
