"""empty message

Revision ID: 7afb9a2fc168
Revises: ba6d87f9d136
Create Date: 2020-12-05 21:01:57.566557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7afb9a2fc168'
down_revision = 'ba6d87f9d136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('difficulty', sa.Integer(), nullable=False))
    op.drop_column('tasks', 'difficult')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('difficult', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'difficulty')
    # ### end Alembic commands ###
