"""empty message

Revision ID: 059b6cd55423
Revises: fca45f45081f
Create Date: 2020-12-04 16:24:05.257670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059b6cd55423'
down_revision = 'fca45f45081f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'messages', 'users', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'id')
    # ### end Alembic commands ###
