"""empty message

Revision ID: 28412c74b0b9
Revises: f3f2cc4df89c
Create Date: 2020-12-04 13:23:45.286817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28412c74b0b9'
down_revision = 'f3f2cc4df89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('hair', sa.String(length=50), nullable=False),
    sa.Column('face', sa.String(length=50), nullable=False),
    sa.Column('body', sa.String(length=50), nullable=False),
    sa.Column('helmet', sa.String(length=50), nullable=True),
    sa.Column('top', sa.String(length=50), nullable=True),
    sa.Column('bottom', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('stats', sa.Column('avatar_id', sa.Integer(), nullable=False))
    op.drop_constraint('stats_user_id_fkey', 'stats', type_='foreignkey')
    op.create_foreign_key(None, 'stats', 'avatars', ['avatar_id'], ['id'])
    op.drop_column('stats', 'user_id')
    op.drop_column('users', 'hair')
    op.drop_column('users', 'exp')
    op.drop_column('users', 'bottom')
    op.drop_column('users', 'helmet')
    op.drop_column('users', 'face')
    op.drop_column('users', 'body')
    op.drop_column('users', 'top')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('top', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('body', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('face', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('helmet', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bottom', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('exp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('hair', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('stats', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.create_foreign_key('stats_user_id_fkey', 'stats', 'users', ['user_id'], ['id'])
    op.drop_column('stats', 'avatar_id')
    op.drop_table('avatars')
    # ### end Alembic commands ###
